sudo: false
language: python
os:
  - linux

git:
  depth: false

addons:
  apt:
    packages:
    - git
    - wget
    - curl
    - libssl-dev
    - libncurses-dev
    - flex
    - bison
    - gperf
    - python
    - python-pip
    - python-setuptools
    - python-serial
    - python-click
    - python-cryptography
    - python-future
    - python-pyparsing
    - python-pyelftools
    - cmake
    - ninja-build
    - ccache

stages:
  - build

jobs:
  include:

    - name: "Build Arduino Libs"
      if: tag IS blank AND (type = pull_request OR (type = push AND branch = master))
      stage: build
      script: bash $TRAVIS_BUILD_DIR/build.sh
